title: About Me # your name (or website title) here
logo: "/images/me.PNG?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
 
  II am a data science professional interested in utilizing data to solve social, economic, and environmental dilemmas. I have a background in geosciences, human geography, and urban planning, where I have learned to solve many spatial analytical problems. I have developed a variety of programming skills, GIS skills, and remote sensing skills suitable to a large variety of industries. I can be of great help in various fields, including machine learning, web development, GIS, environmental science, and city planning. 
  <br><br>
  <a href="www.linkedin.com/in/kyle-mccarthy-9338a8177">View My LinkedIn Profile</a> 
  <br>
  <a href="https://drive.google.com/file/d/1TWhnNVjqKauBx1Z6r2TPx30UOftOJus2/view?usp=sharing">View My Resume</a>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
